version: 3
tasks:
  test:
    dir: .
    env:
      BITBUCKET_APP_PASSWORD: "test"
      BITBUCKET_DISPLAY_NAME: "test"
      BITBUCKET_ENVIRONMENT_NAME: "test"
      BITBUCKET_ENVIRONMENT_NAME_CREATE_VARIABLES: "test"
      BITBUCKET_ENVIRONMENT_NAME_NO_VARIABLES: "test"
      BITBUCKET_ENVIRONMENT_NAME_ONE_VARIABLE: "test"
      BITBUCKET_ENVIRONMENT_NAME_PRODUCTION: "test"
      BITBUCKET_ENVIRONMENT_NAME_STAGING: "test"
      BITBUCKET_ENVIRONMENT_NAME_THREE_VARIABLES: "test"
      BITBUCKET_ENVIRONMENT_NAME_UPDATE_VARIABLES: "test"
      BITBUCKET_ENVIRONMENT_UUID: "test"
      BITBUCKET_ENVIRONMENT_UUID_CREATE_VARIABLES: "test"
      BITBUCKET_ENVIRONMENT_UUID_NO_VARIABLES: "test"
      BITBUCKET_ENVIRONMENT_UUID_ONE_VARIABLE: "test"
      BITBUCKET_ENVIRONMENT_UUID_THREE_VARIABLES: "test"
      BITBUCKET_ENVIRONMENT_UUID_UPDATE_VARIABLES: "test"
      BITBUCKET_REPO_SLUG: "test"
      BITBUCKET_USERNAME: "test"
      BITBUCKET_WORKSPACE_INSECURE_VARIABLE_KEY: "test"
      BITBUCKET_WORKSPACE_INSECURE_VARIABLE_UUID: "test"
      BITBUCKET_WORKSPACE_INSECURE_VARIABLE_VALUE: "test"
      BITBUCKET_WORKSPACE_SECURE_VARIABLE_KEY: "test"
      BITBUCKET_WORKSPACE_SECURE_VARIABLE_UUID: "test"
      BITBUCKET_WORKSPACE_SLUG: "test"
    cmds:
    - go test ./...
